name: "0. Hello World"
run-name: "0. ${{ github.actor }}'s GitHub Actions Hello World ðŸš€"
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "github.actor is ${{ github.actor }}"
      - run: echo "github.event_name is ${{ github.event_name }}"
      - run: echo "runner.os is ${{ runner.os }}"
      - run: echo "github.ref is ${{ github.ref }}"
      - run: echo "github.repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls -al ${{ github.workspace }}
      - run: echo "job.status is ${{ job.status }}."
